### ISSUE TITLE
Allow ssl configuration in ManagementClient

### ISSUE THREAD

**Issue by czuniga9** [storyblok/php-client#39]
Hello,

Currently, the ManagementClient class hardcodes the usage of ssl to `false`, can you add a parameter to make it configurable? Or even better, default to true. 😁
https://github.com/storyblok/php-client/blob/09d6b994d3301454026d6e6249b99b19d746ec2c/src/Storyblok/ManagementClient.php#L23-L26

**Comment by christianzoppi** [comment]
Thanks, @czuniga9! This issue has been fixed by #41. Now you can set up your client and enable ssl by setting to `true` the fourth argument of the contructor:

```php
$managementClient = new \Storyblok\ManagementClient('your-storyblok-oauth-token', 'mapi.storyblok.com', 'v1', true);
```

By default, it's still set to false as we want to make sure that this won't break any current implementation, but now you can finally configure it.
